@echo off

set "SCRIPT_DIR=%~dp0"
set "PROJECT_ROOT=%SCRIPT_DIR%"

set "EXTERNAL_CLEAN_SCRIPT=%PROJECT_ROOT%external\clean_ext.win32.bat"
set "CIVA_EXE_PATH=%PROJECT_ROOT%.out\civa.exe"

set "CIVA_SRC_ROOT=%PROJECT_ROOT%civa"

call "%EXTERNAL_CLEAN_SCRIPT%"

IF EXIST "%CIVA_EXE_PATH%" DEL /F "%CIVA_EXE_PATH%"